// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/channels/slack.ts";
import * as module_3 from "../../agent/connections/context-dev.ts";
import * as module_4 from "../../agent/subagents/copywriting/agent.ts";
import * as module_5 from "../../agent/subagents/copywriting/connections/context-dev.ts";
import * as module_6 from "../../agent/subagents/cro/agent.ts";
import * as module_7 from "../../agent/subagents/cro/connections/context-dev.ts";
import * as module_8 from "../../agent/subagents/growth-retention/agent.ts";
import * as module_9 from "../../agent/subagents/paid-social/agent.ts";
import * as module_10 from "../../agent/subagents/seo-content/agent.ts";
import * as module_11 from "../../agent/subagents/seo-content/connections/context-dev.ts";
import * as module_12 from "../../agent/subagents/strategy-analytics/agent.ts";
import * as module_13 from "../../agent/subagents/strategy-analytics/connections/context-dev.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "channels/slack.ts": module_2,
                  "connections/context-dev.ts": module_3
                })
            }),
      "subagents/copywriting": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_4,
                  "connections/context-dev.ts": module_5
                })
            }),
      "subagents/cro": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_6,
                  "connections/context-dev.ts": module_7
                })
            }),
      "subagents/growth-retention": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_8
                })
            }),
      "subagents/paid-social": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_9
                })
            }),
      "subagents/seo-content": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_10,
                  "connections/context-dev.ts": module_11
                })
            }),
      "subagents/strategy-analytics": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_12,
                  "connections/context-dev.ts": module_13
                })
            })
    })
});

export default moduleMap;
