// Generated by eve. Do not edit by hand.
import { POST } from "./workflows.mjs";
import "../../host/compiled-artifacts-workflow-world.mjs";
import { getWorld as __eveGetWorkflowWorld } from "/vercel/share/v0-project/node_modules/.pnpm/eve@0.22.6_ai@7.0.22_zod@4.4.3__dotenv@17.4.2_drizzle-orm@0.45.2_@types+pg@8.20.0_kysel_2fc2bc58140ad98e61bf40b11d04a760/node_modules/eve/dist/src/internal/workflow/runtime.js";

try {
  const __eveWorkflowWorld = await __eveGetWorkflowWorld();
  if (typeof __eveWorkflowWorld?.registerHandler === "function") {
    __eveWorkflowWorld.registerHandler("__eve6d792d70726f6a656374_wkf_workflow_", POST);
  }
} catch (err) {
  console.warn("[eve] Failed to register direct workflow queue handlers:", err);
}

export default async ({ req }) => {
  return await POST(req);
};
