// Generated by eve. Do not edit by hand.
import { POST } from "../../../node_modules/.pnpm/eve@0.22.6_ai@7.0.22_zod@4.4.3__dotenv@17.4.2_drizzle-orm@0.45.2_@types+pg@8.20.0_kysel_2fc2bc58140ad98e61bf40b11d04a760/node_modules/eve/.eve/workflow-cache/500b4152ebb4/workflows.mjs";

export default async ({ req }) => {
  return await POST(req);
};
