// Generated by eve. Do not edit by hand.
import { POST } from "../../../node_modules/.pnpm/eve@0.22.6_@vercel+blob@2.6.1_ai@7.0.22_zod@4.4.3__dotenv@17.4.2_drizzle-orm@0.45.2_@ty_ca0d2db8f0586b91a9f623bcf8d9c329/node_modules/eve/.eve/workflow-cache/500b4152ebb4/workflows.mjs";

export default async ({ req }) => {
  return await POST(req);
};
